spring:
  application:
    name: RentWise

  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

  mail:
    host: smtp.gmail.com
    port: 587
    username: usr
    password: pass


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

    scheduling:
      enabled: false # Set to true to enable email scheduling

notification:
  email:
#    cron: "0 0 9 1 * ?" # At 9 AM on the 1st day of each month
    cron: "*/10 * * * * *" # Run every 10 seconds for testing


jwtSecret: aHR0cHM6Ly93d3cueW91YmlsdW1hbWVyaWNhLmNvbS9sb2dpbi8=
jwtExpirationMs: 86400000
